services:
  game-server:
    build: .
    restart: unless-stopped

    ports:
      - "127.0.0.1:3452:3000"

    environment:
      - NODE_ENV=production

    volumes:
      - database:/app/data

volumes:
  database:
